name: Update Discord Messages

on:
  push:
    branches:
      - main
      - add-role-messages
    paths:
      - 'messages/**'

jobs:
  update-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Update Discord
        uses: compsoc-edinburgh/discord-post-updater@xml-specs
        with:
          discord_token: ${{ secrets.discord_bot_token }}
          post_xml: messages/pronouns.xml
          discord_channel: '765660106259562501' # N.B. The quote marks here are required
          discord_message: new # Optional, use quotes if specifying an ID
