name: Update Discord Messages

on:
  push:
    branches:
      - main
    paths:
      - 'messages/**'

jobs:
  update-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: none
          filters: |
            readme:
              - 'messages/readme.xml'
            pronouns:
              - 'messages/pronouns.xml'
            year:
              - 'messages/year.xml'
            protectedgroups:
              - 'messages/protectedgroups.xml'

      - name: Update main README message
        uses: compsoc-edinburgh/discord-post-updater@xml-specs
        if: steps.changes.outputs.readme == 'true'
        with:
          discord_token: ${{ secrets.discord_bot_token }}
          post_xml: messages/readme.xml
          discord_channel: '993137907378442240' # N.B. The quote marks here are required
          discord_message: '1007932938102513724' # Optional, use quotes if specifying an ID

      - name: Update Pronouns
        uses: compsoc-edinburgh/discord-post-updater@xml-specs
        if: steps.changes.outputs.pronouns == 'true'
        with:
          discord_token: ${{ secrets.discord_bot_token }}
          post_xml: messages/pronouns.xml
          discord_channel: '993137907378442240' # N.B. The quote marks here are required
          discord_message: '1007933023221723157' # Optional, use quotes if specifying an ID

      - name: Update Academic Year
        uses: compsoc-edinburgh/discord-post-updater@xml-specs
        if: steps.changes.outputs.year == 'true'
        with:
          discord_token: ${{ secrets.discord_bot_token }}
          post_xml: messages/year.xml
          discord_channel: '993137907378442240' # N.B. The quote marks here are required
          discord_message: '1007933024106725476' # Optional, use quotes if specifying an ID

      - name: Update Protected Groups
        uses: compsoc-edinburgh/discord-post-updater@xml-specs
        if: steps.changes.outputs.protectedgroups == 'true'
        with:
          discord_token: ${{ secrets.discord_bot_token }}
          post_xml: messages/protectedgroups.xml
          discord_channel: '993137907378442240' # N.B. The quote marks here are required
          discord_message: '1007933024740057089' # Optional, use quotes if specifying an ID
